# сервис-аккаунт с правами для cronjob
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cronjob-sa
    namespace: default
roleRef:
  kind: Role
  name: cronjob-role
  apiGroup: rbac.authorization.k8s.io
